version: '3'
 
networks:
  monitoring: {}
 
volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  blackbox:
    image: prom/blackbox-exporter:v0.22.0
    container_name: blackbox
    restart: unless-stopped
    ports:
      - '9115:9115'
    networks:
      - monitoring
    volumes:
      - ./config/blackbox.yml:/etc/blackbox_exporter/config.yml

  prometheus:
      image: prom/prometheus:v2.38.0
      container_name: prometheus
      restart: unless-stopped
      ports:
        - '9090:9090'
      networks:
        - monitoring
      volumes:
        - prometheus_data:/prometheus
        - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./config/alertrules.yml:/etc/prometheus/alertrules.yml
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--web.enable-lifecycle"
  grafana:
      image: grafana/grafana:9.1.1
      container_name: grafana
      restart: unless-stopped
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=password
        - GF_USERS_ALLOW_SIGN_UP=false
      depends_on:
        - prometheus
      volumes:
        - grafana_data:/var/lib/grafana
        - ./config/grafana/provisioning:/etc/grafana/provisioning
      ports:
        - "3000:3000"
        